name: HeadsAnywhere
version: '${project.version}'
main: ru.omashune.headsanywhere.HeadsAnywhere
api-version: 1.16

depend:
  - SkinsRestorer

softdepend:
  - PlaceholderAPI

authors: [ omashune, 0diador ]
description: Use players' heads anywhere!
website: https://github.com/0diador
